# HLint configuration file
# https://github.com/ndmitchell/hlint
##########################

- modules:
  - {name: Control.Arrow, within: []} # Certain modules are banned entirely

# - group: {name: dollar,     enabled: true}
- group: {name: generalise, enabled: true}

- ignore: {name: "Use &&&"}
- ignore: {name: "Use <>"}
- ignore: {name: "Use <$>"}
